"""Build and atomically publish the deterministic project record index."""

from __future__ import annotations

import os
from pathlib import Path
import secrets
import stat

from .record import PolicyError
from .tree import record_tree_digest, validate_record_tree


INDEX_BANNER = (
    "# Didimlog project index — generated by didim index; do not edit by hand"
)
DIGEST_PREFIX = "# canonical-record-tree-digest: "
INDEX_COLUMNS = (
    "scope",
    "negative-rank",
    "status-rank",
    "status",
    "updated",
    "id",
    "type",
    "title",
    "comma-separated-tags",
)
INDEX_HEADER = "\t".join(INDEX_COLUMNS)
STATUS_RANK = {
    "validated": 0,
    "refuted": 1,
    "running": 2,
    "draft": 3,
    "superseded": 4,
}
_ROW_FORBIDDEN = ("\t", "\n", "\r")


def _guard_field(value, record_id):
    """Reject a field that would make the fixed-width TSV row ambiguous."""
    text = str(value)
    if any(delimiter in text for delimiter in _ROW_FORBIDDEN):
        raise PolicyError("AMBIGUOUS_ROW {}".format(record_id))
    return text


def _negative_rank(record) -> int:
    if record["status"] == "refuted":
        return 0
    if record["type"] == "experiment" and record.get("result") == "failure":
        return 0
    return 1


def _build_row(record) -> str:
    record_id = record["id"]
    fields = (
        record["scope"],
        _negative_rank(record),
        STATUS_RANK[record["status"]],
        record["status"],
        record["updated"],
        record_id,
        record["type"],
        record["title"],
        ",".join(record["tags"]),
    )
    return "\t".join(_guard_field(field, record_id) for field in fields)


def build_index_bytes(workspace: Path) -> bytes:
    """Validate the complete tree and return byte-stable UTF-8/LF index bytes."""
    records = validate_record_tree(workspace)
    digest = record_tree_digest(records)
    lines = [INDEX_BANNER, DIGEST_PREFIX + digest, INDEX_HEADER]
    lines.extend(_build_row(record) for record in sorted(records, key=lambda item: item["id"]))
    return ("\n".join(lines) + "\n").encode("utf-8")


def _output_path(workspace: Path) -> Path:
    return Path(os.path.abspath(workspace)) / "knowledge" / "index" / "INDEX.md"


def _is_within(parent: Path, child: Path) -> bool:
    try:
        return os.path.commonpath((os.fspath(parent), os.fspath(child))) == os.fspath(
            parent
        )
    except ValueError:
        return False


def _validate_output_target(workspace: Path, output: Path) -> None:
    records = (Path(os.path.abspath(workspace)) / "knowledge" / "records").resolve(
        strict=False
    )
    resolved_output = output.resolve(strict=False)
    if _is_within(records, resolved_output):
        raise PolicyError("OUTPUT_IN_RECORDS {}".format(output))


def _directory_flags() -> int:
    return (
        os.O_RDONLY
        | getattr(os, "O_DIRECTORY", 0)
        | getattr(os, "O_NOFOLLOW", 0)
    )


def _open_directory_at(parent: int, name: str, path: Path) -> int:
    try:
        linked = os.stat(name, dir_fd=parent, follow_symlinks=False)
        descriptor = os.open(name, _directory_flags(), dir_fd=parent)
    except OSError as error:
        raise PolicyError("INDEX_PATH_UNSAFE {}".format(path)) from error
    opened = os.fstat(descriptor)
    if (
        stat.S_ISLNK(linked.st_mode)
        or not stat.S_ISDIR(opened.st_mode)
        or opened.st_dev != linked.st_dev
        or opened.st_ino != linked.st_ino
    ):
        os.close(descriptor)
        raise PolicyError("INDEX_PATH_UNSAFE {}".format(path))
    return descriptor


def _open_index_directory(workspace: Path) -> tuple[int, Path]:
    root = Path(os.path.abspath(workspace))
    output = _output_path(root)
    _validate_output_target(root, output)
    try:
        linked = root.lstat()
        workspace_descriptor = os.open(root, _directory_flags())
    except OSError as error:
        raise PolicyError("INDEX_PATH_UNSAFE {}".format(root)) from error
    opened = os.fstat(workspace_descriptor)
    if (
        stat.S_ISLNK(linked.st_mode)
        or not stat.S_ISDIR(opened.st_mode)
        or opened.st_dev != linked.st_dev
        or opened.st_ino != linked.st_ino
    ):
        os.close(workspace_descriptor)
        raise PolicyError("INDEX_PATH_UNSAFE {}".format(root))

    knowledge_descriptor: int | None = None
    index_descriptor: int | None = None
    try:
        knowledge = root / "knowledge"
        knowledge_descriptor = _open_directory_at(
            workspace_descriptor,
            "knowledge",
            knowledge,
        )
        try:
            os.mkdir("index", 0o755, dir_fd=knowledge_descriptor)
        except FileExistsError:
            pass
        except OSError as error:
            raise PolicyError("INDEX_PATH_UNSAFE {}".format(output.parent)) from error
        index_descriptor = _open_directory_at(
            knowledge_descriptor,
            "index",
            output.parent,
        )
        try:
            existing = os.stat(
                "INDEX.md",
                dir_fd=index_descriptor,
                follow_symlinks=False,
            )
        except FileNotFoundError:
            existing = None
        if existing is not None and (
            stat.S_ISLNK(existing.st_mode) or not stat.S_ISREG(existing.st_mode)
        ):
            raise PolicyError("INDEX_PATH_UNSAFE {}".format(output))
        return index_descriptor, output
    except BaseException:
        if index_descriptor is not None:
            os.close(index_descriptor)
        raise
    finally:
        if knowledge_descriptor is not None:
            os.close(knowledge_descriptor)
        os.close(workspace_descriptor)


def _write_all(descriptor: int, data: bytes) -> None:
    remaining = memoryview(data)
    while remaining:
        written = os.write(descriptor, remaining)
        if written <= 0:
            raise OSError("short write")
        remaining = remaining[written:]
    os.fsync(descriptor)


def write_index(workspace: Path) -> Path:
    """Replace the fixed project index only after complete tree validation."""
    _validate_output_target(Path(workspace), _output_path(Path(workspace)))
    data = build_index_bytes(workspace)
    directory_descriptor, output = _open_index_directory(Path(workspace))
    temporary_name: str | None = None
    temporary_descriptor: int | None = None
    try:
        for _ in range(32):
            temporary_name = ".didim-index-{}.tmp".format(secrets.token_hex(12))
            try:
                temporary_descriptor = os.open(
                    temporary_name,
                    os.O_WRONLY
                    | os.O_CREAT
                    | os.O_EXCL
                    | getattr(os, "O_CLOEXEC", 0)
                    | getattr(os, "O_NOFOLLOW", 0),
                    0o600,
                    dir_fd=directory_descriptor,
                )
                break
            except FileExistsError:
                temporary_name = None
        if temporary_descriptor is None or temporary_name is None:
            raise OSError("could not allocate index temporary file")
        _write_all(temporary_descriptor, data)
        os.close(temporary_descriptor)
        temporary_descriptor = None
        os.replace(
            temporary_name,
            "INDEX.md",
            src_dir_fd=directory_descriptor,
            dst_dir_fd=directory_descriptor,
        )
        temporary_name = None
        os.fsync(directory_descriptor)
        return output
    finally:
        if temporary_descriptor is not None:
            os.close(temporary_descriptor)
        if temporary_name is not None:
            try:
                os.unlink(temporary_name, dir_fd=directory_descriptor)
            except OSError:
                pass
        os.close(directory_descriptor)


def check_index(workspace: Path) -> int:
    """Return zero only when the fixed index already matches current records."""
    expected = build_index_bytes(workspace)
    output = _output_path(Path(workspace))
    _validate_output_target(Path(workspace), output)
    try:
        linked = output.lstat()
    except FileNotFoundError:
        return 1
    if stat.S_ISLNK(linked.st_mode) or not stat.S_ISREG(linked.st_mode):
        raise PolicyError("INDEX_PATH_UNSAFE {}".format(output))
    try:
        actual = output.read_bytes()
    except OSError as error:
        raise PolicyError("INDEX_PATH_UNSAFE {}".format(output)) from error
    return 0 if actual == expected else 1
