import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from didimlog.errors import DidimError
from didimlog.project import index as project_index
from didimlog.project.index import build_index_bytes, check_index, write_index


DATE = "2026-07-14"
BANNER = "# Didimlog project index — generated by didim index; do not edit by hand"
DIGEST_PREFIX = "# canonical-record-tree-digest: "
COLUMNS = (
    "scope",
    "negative-rank",
    "status-rank",
    "status",
    "updated",
    "id",
    "type",
    "title",
    "comma-separated-tags",
)
HEADER = "\t".join(COLUMNS)


def _toml_value(value):
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (list, tuple)):
        return "[{}]".format(
            ", ".join(json.dumps(item, ensure_ascii=False) for item in value)
        )
    raise TypeError("unsupported fixture value: {!r}".format(value))


def _record_bytes(
    record_id,
    record_type,
    *,
    title,
    status="draft",
    version=1,
    tags=(),
    result="success",
    review_by=None,
    supersedes=None,
    superseded_by=None,
    artifact_path=None,
    artifact_sha256=None,
    artifact_git=None,
):
    fields = [
        ("schema_version", 1),
        ("id", record_id),
        ("type", record_type),
        ("title", title),
        ("status", status),
        ("scope", "project"),
        ("created", DATE),
        ("updated", DATE),
        ("version", version),
        ("tags", list(tags)),
        ("sources", []),
    ]
    if review_by is not None:
        fields.append(("review_by", review_by))
    if supersedes is not None:
        fields.append(("supersedes", supersedes))
    if superseded_by is not None:
        fields.append(("superseded_by", superseded_by))
    if record_type == "evidence":
        fields.append(("artifact_path", artifact_path))
        if artifact_sha256 is not None:
            fields.append(("artifact_sha256", artifact_sha256))
        if artifact_git is not None:
            fields.append(("artifact_git", artifact_git))

    frontmatter = "\n".join(
        ["+++"]
        + ["{} = {}".format(key, _toml_value(value)) for key, value in fields]
        + ["+++"]
    )
    if record_type == "observation":
        body = "## Observation\n\n{} body\n".format(title)
    elif record_type == "experiment":
        body = (
            "## Hypothesis\n\nH\n\n"
            "## Method\n\nM\n\n"
            "## Result\n\n{}\n\n"
            "## Interpretation\n\nContradicts: none\n\nI\n"
        ).format(result)
    else:
        body = (
            "## Artifact\n\n{}\n\n"
            "## Origin\n\nlocal fixture\n\n"
            "## Collection\n\ntest\n"
        ).format(artifact_path)
    return (frontmatter + "\n\n" + body).encode("utf-8")


def _write_record(
    workspace,
    record_id,
    record_type,
    *,
    artifact_bytes=b"artifact\n",
    artifact_git=None,
    **options,
):
    if record_type == "evidence":
        artifact_path = options.setdefault(
            "artifact_path", "knowledge/raw/data/{}.bin".format(record_id)
        )
        if artifact_git is None:
            artifact = workspace / artifact_path
            artifact.parent.mkdir(parents=True, exist_ok=True)
            artifact.write_bytes(artifact_bytes)
            options["artifact_sha256"] = hashlib.sha256(artifact_bytes).hexdigest()
        else:
            options["artifact_git"] = artifact_git

    path = (
        workspace
        / "knowledge"
        / "records"
        / record_type
        / "{}.md".format(record_id)
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(_record_bytes(record_id, record_type, **options))
    return path


def _tree_digest(workspace):
    records = []
    root = workspace / "knowledge" / "records"
    for path in root.glob("*/*.md"):
        records.append((path.stem, path.read_bytes()))
    parts = [
        "{}\t{}\n".format(record_id, hashlib.sha256(raw).hexdigest()).encode(
            "utf-8"
        )
        for record_id, raw in sorted(records)
    ]
    return hashlib.sha256(b"".join(parts)).hexdigest()


class ProjectIndexByteContractTests(unittest.TestCase):
    def test_exact_nine_field_bytes_cover_canonical_ranks_and_order(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "workspace"
            _write_record(
                workspace,
                "OBS-20260714-06",
                "observation",
                title="확정 관찰",
                status="validated",
                supersedes="OBS-20260714-05",
            )
            _write_record(
                workspace,
                "EXP-20260714-02",
                "experiment",
                title="실패 실험",
                status="running",
                tags=("negative",),
                result="failure",
            )
            _write_record(
                workspace,
                "OBS-20260714-05",
                "observation",
                title="대체된 관찰",
                status="superseded",
                version=2,
                superseded_by="OBS-20260714-06",
            )
            _write_record(
                workspace,
                "EVD-20260714-03",
                "evidence",
                title="초안 근거",
                status="draft",
                tags=("evidence", "한글"),
                review_by="2000-01-01",
            )
            _write_record(
                workspace,
                "OBS-20260714-04",
                "observation",
                title="반박된 관찰",
                status="refuted",
            )

            digest = _tree_digest(workspace)
            rows = [
                "project\t1\t3\tdraft\t2026-07-14\tEVD-20260714-03\tevidence\t초안 근거\tevidence,한글",
                "project\t0\t2\trunning\t2026-07-14\tEXP-20260714-02\texperiment\t실패 실험\tnegative",
                "project\t0\t1\trefuted\t2026-07-14\tOBS-20260714-04\tobservation\t반박된 관찰\t",
                "project\t1\t4\tsuperseded\t2026-07-14\tOBS-20260714-05\tobservation\t대체된 관찰\t",
                "project\t1\t0\tvalidated\t2026-07-14\tOBS-20260714-06\tobservation\t확정 관찰\t",
            ]
            expected = (
                "\n".join([BANNER, DIGEST_PREFIX + digest, HEADER] + rows) + "\n"
            ).encode("utf-8")

            first = build_index_bytes(workspace)
            second = build_index_bytes(workspace)

            self.assertEqual(first, expected)
            self.assertEqual(second, expected)
            self.assertEqual(first.decode("utf-8").encode("utf-8"), first)
            self.assertNotIn(b"\r", first)
            self.assertNotIn(b"stale", first)
            self.assertNotIn(b"review_by", first)
            for row in first.split(b"\n")[3:-1]:
                self.assertEqual(row.count(b"\t"), 8)

    def test_post_validation_field_guard_rejects_tsv_delimiters(self):
        for delimiter in ("\t", "\r", "\n"):
            with self.subTest(delimiter=repr(delimiter)):
                with self.assertRaises(DidimError) as caught:
                    project_index._guard_field(
                        "before{}after".format(delimiter), "OBS-20260714-90"
                    )
                self.assertEqual(
                    caught.exception.token, "AMBIGUOUS_ROW OBS-20260714-90"
                )
                self.assertEqual(caught.exception.exit_code, 3)


class ProjectIndexWriteContractTests(unittest.TestCase):
    def test_existing_index_survives_validation_and_atomic_replace_failures(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "workspace"
            record_path = _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="valid",
            )
            output = workspace / "knowledge" / "index" / "INDEX.md"
            output.parent.mkdir(parents=True)
            output.write_bytes(b"OLD-INDEX\n")

            record_path.write_bytes(b"not a canonical record\n")
            with self.assertRaises(DidimError):
                write_index(workspace)
            self.assertEqual(output.read_bytes(), b"OLD-INDEX\n")

            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="valid",
            )
            with mock.patch(
                "didimlog.project.index.os.replace",
                side_effect=OSError("replace failed"),
            ):
                with self.assertRaises(OSError):
                    write_index(workspace)
            self.assertEqual(output.read_bytes(), b"OLD-INDEX\n")

    def test_output_resolving_inside_records_is_refused_before_write(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "workspace"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="valid",
            )
            records_directory = workspace / "knowledge" / "records" / "observation"
            index_directory = workspace / "knowledge" / "index"
            index_directory.symlink_to(records_directory, target_is_directory=True)
            redirected_output = records_directory / "INDEX.md"
            redirected_output.write_bytes(b"USER-DATA\n")

            with self.assertRaises(DidimError) as caught:
                write_index(workspace)

            self.assertIn("OUTPUT_IN_RECORDS", caught.exception.token)
            self.assertEqual(caught.exception.exit_code, 3)
            self.assertEqual(redirected_output.read_bytes(), b"USER-DATA\n")

    def test_check_distinguishes_missing_current_and_stale_without_writing(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "workspace"
            record_path = _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="first",
            )
            output = workspace / "knowledge" / "index" / "INDEX.md"

            self.assertEqual(check_index(workspace), 1)
            self.assertFalse(output.exists())

            self.assertEqual(write_index(workspace), output)
            current = output.read_bytes()
            self.assertEqual(check_index(workspace), 0)

            record_path.write_bytes(
                _record_bytes(
                    "OBS-20260714-01", "observation", title="changed"
                )
            )
            self.assertEqual(check_index(workspace), 1)
            self.assertEqual(output.read_bytes(), current)

    def test_public_index_surfaces_reject_workspace_path_replacement(self):
        for operation in (write_index, check_index):
            with self.subTest(operation=operation.__name__):
                with tempfile.TemporaryDirectory() as temp_dir:
                    root = Path(temp_dir)
                    workspace = root / "workspace"
                    replacement = root / "replacement"
                    _write_record(
                        workspace,
                        "OBS-20260714-01",
                        "observation",
                        title="original",
                    )
                    _write_record(
                        replacement,
                        "OBS-20260714-01",
                        "observation",
                        title="replacement",
                    )
                    write_index(workspace)
                    original_index = workspace / "knowledge/index/INDEX.md"
                    original_index.write_bytes(b"stale original index\n")
                    original_before = original_index.read_bytes()
                    write_index(replacement)
                    workspace_backup = root / "workspace.original"
                    real_acquire = project_index.acquire_directory_lock
                    replaced = False

                    def replace_workspace_then_lock(descriptor, **kwargs):
                        nonlocal replaced
                        if not replaced:
                            workspace.rename(workspace_backup)
                            replacement.rename(workspace)
                            replaced = True
                        return real_acquire(descriptor, **kwargs)

                    try:
                        with mock.patch.object(
                            project_index,
                            "acquire_directory_lock",
                            side_effect=replace_workspace_then_lock,
                        ):
                            with self.assertRaises(DidimError) as caught:
                                operation(workspace)
                        self.assertIn("INDEX_PATH_UNSAFE", caught.exception.token)
                        self.assertEqual(caught.exception.exit_code, 3)
                    finally:
                        self.assertEqual(
                            (
                                workspace_backup / "knowledge/index/INDEX.md"
                            ).read_bytes(),
                            original_before,
                        )
                        if replaced:
                            workspace.rename(replacement)
                            workspace_backup.rename(workspace)

    def test_public_write_rejects_workspace_replacement_during_build_before_publish(
        self,
    ):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            workspace = root / "workspace"
            replacement = root / "replacement"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="original",
            )
            _write_record(
                replacement,
                "OBS-20260714-01",
                "observation",
                title="replacement",
            )
            write_index(workspace)
            write_index(replacement)
            original_index = workspace / "knowledge/index/INDEX.md"
            original_index.write_bytes(b"stale original index\n")
            original_before = original_index.read_bytes()
            workspace_backup = root / "workspace.original"
            real_build = project_index.build_index_bytes
            replaced = False

            def replace_workspace_after_build(pinned):
                nonlocal replaced
                data = real_build(pinned)
                workspace.rename(workspace_backup)
                replacement.rename(workspace)
                replaced = True
                return data

            try:
                with mock.patch.object(
                    project_index,
                    "build_index_bytes",
                    side_effect=replace_workspace_after_build,
                ):
                    with self.assertRaises(DidimError) as caught:
                        write_index(workspace)
                self.assertIn("INDEX_PATH_UNSAFE", caught.exception.token)
                self.assertEqual(caught.exception.exit_code, 3)
                self.assertEqual(
                    (
                        workspace_backup / "knowledge/index/INDEX.md"
                    ).read_bytes(),
                    original_before,
                )
            finally:
                if replaced:
                    workspace.rename(replacement)
                    workspace_backup.rename(workspace)

    def test_public_write_rolls_back_if_workspace_detaches_at_publish(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            workspace = root / "workspace"
            replacement = root / "replacement"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="original",
            )
            _write_record(
                replacement,
                "OBS-20260714-01",
                "observation",
                title="replacement",
            )
            write_index(workspace)
            write_index(replacement)
            original_index = workspace / "knowledge/index/INDEX.md"
            original_index.write_bytes(b"stale original index\n")
            original_before = original_index.read_bytes()
            workspace_backup = root / "workspace.original"
            real_require = project_index._require_pinned_knowledge
            required_path_checks = 0
            replaced = False

            def replace_workspace_after_last_check(*args, **kwargs):
                nonlocal required_path_checks, replaced
                result = real_require(*args, **kwargs)
                if kwargs.get("require_workspace_path"):
                    required_path_checks += 1
                    if required_path_checks == 3:
                        workspace.rename(workspace_backup)
                        replacement.rename(workspace)
                        replaced = True
                return result

            try:
                with mock.patch.object(
                    project_index,
                    "_require_pinned_knowledge",
                    side_effect=replace_workspace_after_last_check,
                ):
                    with self.assertRaises(DidimError) as caught:
                        write_index(workspace)
                self.assertIn("INDEX_PATH_UNSAFE", caught.exception.token)
                self.assertEqual(caught.exception.exit_code, 3)
                self.assertEqual(
                    (
                        workspace_backup / "knowledge/index/INDEX.md"
                    ).read_bytes(),
                    original_before,
                )
            finally:
                if replaced:
                    workspace.rename(replacement)
                    workspace_backup.rename(workspace)

    def test_public_write_removes_new_index_if_workspace_detaches_at_publish(
        self,
    ):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            workspace = root / "workspace"
            replacement = root / "replacement"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="original",
            )
            _write_record(
                replacement,
                "OBS-20260714-01",
                "observation",
                title="replacement",
            )
            write_index(replacement)
            workspace_backup = root / "workspace.original"
            real_require = project_index._require_pinned_knowledge
            required_path_checks = 0
            replaced = False

            def replace_workspace_after_last_check(*args, **kwargs):
                nonlocal required_path_checks, replaced
                result = real_require(*args, **kwargs)
                if kwargs.get("require_workspace_path"):
                    required_path_checks += 1
                    if required_path_checks == 3:
                        workspace.rename(workspace_backup)
                        replacement.rename(workspace)
                        replaced = True
                return result

            try:
                with mock.patch.object(
                    project_index,
                    "_require_pinned_knowledge",
                    side_effect=replace_workspace_after_last_check,
                ):
                    with self.assertRaises(DidimError) as caught:
                        write_index(workspace)
                self.assertIn("INDEX_PATH_UNSAFE", caught.exception.token)
                self.assertEqual(caught.exception.exit_code, 3)
                self.assertFalse(
                    (
                        workspace_backup / "knowledge/index/INDEX.md"
                    ).exists()
                )
            finally:
                if replaced:
                    workspace.rename(replacement)
                    workspace_backup.rename(workspace)


    def test_public_write_treats_inner_fsync_as_commit_boundary(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            workspace = root / "workspace"
            replacement = root / "replacement"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="original",
            )
            _write_record(
                replacement,
                "OBS-20260714-01",
                "observation",
                title="replacement",
            )
            write_index(replacement)
            workspace_backup = root / "workspace.original"
            real_write = project_index._write_index_locked
            replaced = False

            def replace_workspace_after_commit(*args, **kwargs):
                nonlocal replaced
                output = real_write(*args, **kwargs)
                workspace.rename(workspace_backup)
                replacement.rename(workspace)
                replaced = True
                return output

            try:
                with mock.patch.object(
                    project_index,
                    "_write_index_locked",
                    side_effect=replace_workspace_after_commit,
                ):
                    self.assertEqual(
                        write_index(workspace),
                        workspace / "knowledge/index/INDEX.md",
                    )
                self.assertIn(
                    b"original",
                    (
                        workspace_backup / "knowledge/index/INDEX.md"
                    ).read_bytes(),
                )
            finally:
                if replaced:
                    workspace.rename(replacement)
                    workspace_backup.rename(workspace)

    def test_public_write_preserves_original_error_if_rollback_fails(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            workspace = root / "workspace"
            replacement = root / "replacement"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="original",
            )
            _write_record(
                replacement,
                "OBS-20260714-01",
                "observation",
                title="replacement",
            )
            write_index(workspace)
            write_index(replacement)
            workspace_backup = root / "workspace.original"
            real_require = project_index._require_pinned_knowledge
            real_open = os.open
            required_path_checks = 0
            opened_descriptors = []
            replaced = False

            def replace_workspace_after_last_check(*args, **kwargs):
                nonlocal required_path_checks, replaced
                result = real_require(*args, **kwargs)
                if kwargs.get("require_workspace_path"):
                    required_path_checks += 1
                    if required_path_checks == 3:
                        workspace.rename(workspace_backup)
                        replacement.rename(workspace)
                        replaced = True
                return result

            def track_open(*args, **kwargs):
                descriptor = real_open(*args, **kwargs)
                opened_descriptors.append(descriptor)
                return descriptor

            try:
                with mock.patch.object(
                    project_index,
                    "_require_pinned_knowledge",
                    side_effect=replace_workspace_after_last_check,
                ), mock.patch.object(
                    project_index,
                    "_rollback_index_publication",
                    side_effect=OSError("rollback failed"),
                ), mock.patch.object(
                    project_index.os,
                    "open",
                    side_effect=track_open,
                ):
                    with self.assertRaises(DidimError) as caught:
                        write_index(workspace)
                self.assertIn("INDEX_PATH_UNSAFE", caught.exception.token)
                self.assertEqual(caught.exception.exit_code, 3)
                for descriptor in opened_descriptors:
                    with self.assertRaises(OSError):
                        os.fstat(descriptor)
            finally:
                if replaced:
                    workspace.rename(replacement)
                    workspace_backup.rename(workspace)

    def test_backup_link_is_removed_if_prepublication_sync_fails(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "workspace"
            _write_record(
                workspace,
                "OBS-20260714-01",
                "observation",
                title="original",
            )
            write_index(workspace)
            output = workspace / "knowledge/index/INDEX.md"
            original = output.read_bytes()
            real_link = os.link
            real_fsync = os.fsync
            backup_linked = False

            def track_backup_link(*args, **kwargs):
                nonlocal backup_linked
                result = real_link(*args, **kwargs)
                backup_linked = True
                return result

            def fail_after_backup_link(descriptor):
                if backup_linked:
                    raise OSError("directory fsync failed")
                return real_fsync(descriptor)

            with mock.patch.object(
                project_index.os,
                "link",
                side_effect=track_backup_link,
            ), mock.patch.object(
                project_index.os,
                "fsync",
                side_effect=fail_after_backup_link,
            ):
                with self.assertRaises(OSError):
                    write_index(workspace)

            self.assertEqual(output.read_bytes(), original)
            self.assertEqual(
                [
                    path.name
                    for path in output.parent.iterdir()
                    if path.name.endswith(".bak")
                ],
                [],
            )

class ProjectIndexGitContractTests(unittest.TestCase):
    def test_git_evidence_fails_closed_when_git_is_unavailable(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "workspace"
            home = Path(temp_dir) / "home"
            home.mkdir()
            _write_record(
                workspace,
                "EVD-20260714-01",
                "evidence",
                title="git evidence",
                artifact_git="0" * 40,
            )

            with mock.patch.dict(
                os.environ,
                {"HOME": str(home), "GIT_CONFIG_NOSYSTEM": "1"},
                clear=False,
            ), mock.patch(
                "didimlog.project.artifacts.shutil.which", return_value=None
            ):
                with self.assertRaises(DidimError) as caught:
                    build_index_bytes(workspace)

            self.assertEqual(
                caught.exception.token, "GIT_UNAVAILABLE EVD-20260714-01"
            )
            self.assertEqual(caught.exception.exit_code, 7)

    @unittest.skipUnless(shutil.which("git"), "git required")
    def test_public_index_surfaces_reject_external_git_alternates(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            workspace = root / "workspace"
            replacement = root / "replacement"
            workspace.mkdir()
            replacement.mkdir()
            subprocess.run(["git", "init", "-q", str(workspace)], check=True)
            subprocess.run(["git", "init", "-q", str(replacement)], check=True)

            artifact_path = "knowledge/raw/data/replacement-only.bin"
            artifact = replacement / artifact_path
            artifact.parent.mkdir(parents=True)
            artifact.write_bytes(b"replacement-only artifact\n")
            git_environment = os.environ.copy()
            git_environment.update(
                {
                    "GIT_AUTHOR_NAME": "Didimlog Tests",
                    "GIT_AUTHOR_EMAIL": "didimlog-tests@example.invalid",
                    "GIT_COMMITTER_NAME": "Didimlog Tests",
                    "GIT_COMMITTER_EMAIL": "didimlog-tests@example.invalid",
                }
            )
            subprocess.run(
                ["git", "-C", str(replacement), "add", "--", artifact_path],
                check=True,
                env=git_environment,
            )
            subprocess.run(
                [
                    "git",
                    "-C",
                    str(replacement),
                    "-c",
                    "commit.gpgsign=false",
                    "commit",
                    "-q",
                    "-m",
                    "replacement",
                ],
                check=True,
                env=git_environment,
            )
            replacement_commit = subprocess.run(
                ["git", "-C", str(replacement), "rev-parse", "HEAD"],
                check=True,
                capture_output=True,
                text=True,
            ).stdout.strip()
            alternates = workspace / ".git" / "objects" / "info" / "alternates"
            alternates.write_text(
                str(replacement / ".git" / "objects") + "\n",
                encoding="utf-8",
            )
            _write_record(
                workspace,
                "EVD-20260714-01",
                "evidence",
                title="external alternate",
                artifact_path=artifact_path,
                artifact_git=replacement_commit,
            )
            output = workspace / "knowledge" / "index" / "INDEX.md"
            output.parent.mkdir(parents=True)
            output.write_bytes(build_index_bytes(workspace))

            for operation in (write_index, check_index):
                with self.subTest(operation=operation.__name__):
                    with self.assertRaises(DidimError) as caught:
                        operation(workspace)
                    self.assertEqual(
                        caught.exception.token,
                        "GIT_UNVERIFIABLE EVD-20260714-01",
                    )
                    self.assertEqual(caught.exception.exit_code, 7)


if __name__ == "__main__":
    unittest.main()
